name: Update the container calculator

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Check
        uses: actions/checkout@v3
      -      
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./sources
          file: ./sources/Dockerfile
          push: true
          tags: karimamahgoune123/calculat:1.0.${{github.run_number}}
